<a href="https://colab.research.google.com/github/srikanthravipati27/ml/blob/main/l_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5.0],dtype=np.int8)
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],dtype=complex)
arr3=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [10, 11, 12]]])

In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
arr2

1
2
3
(5,)
(4, 4)
(2, 2, 3)


array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j],
       [13.+0.j, 14.+0.j, 15.+0.j, 16.+0.j]])

In [ ]:
arr1.dtype.itemsize  #

1

In [ ]:
arr1.data

In [ ]:
np.empty((2,3),dtype=int)

array([[      388210083,               0,            6224],
       [      385008774, 140220850448045,      4294967297]])

In [ ]:
np.arange(5,30,4,dtype=float)
np.arange(0,2,0.9)

array([0. , 0.9, 1.8])

In [ ]:
from numpy import pi
np.linspace(0, 2, 9)
x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)
print(x)
print(f)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [ ]:
np.fromfunction(lambda i, j: 10*i + j, (3, 3))


array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.]])

In [ ]:
rng=np.random.default_rng()
rng.random(5)

array([0.49470964, 0.1099979 , 0.01546285, 0.37734658, 0.22512754])

In [ ]:
rng.normal(loc=0, scale=1, size=5)


array([-0.95564407, -1.08792352, -0.34930534,  0.90819114, -1.19016583])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a=a.reshape(2,2,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
a=np.arange(5)
b=np.linspace(0,7,5,dtype=int)
print(b-a)
print(a**2)
print(b>8)

[0 0 1 2 3]
[ 0  1  4  9 16]
[False False False False False]


In [ ]:
ar1=np.arange(4).reshape(2,2)
ar2=np.linspace(2,7,4,dtype=int).reshape(2,2)
print(ar1)
print(ar2)
print(ar1*ar2)
print(ar1@ar2)
print(ar1.dot(ar2))

[[0 1]
 [2 3]]
[[2 3]
 [5 7]]
[[ 0  3]
 [10 21]]
[[ 5  7]
 [19 27]]
[[ 5  7]
 [19 27]]


In [ ]:
a=np.eye(4)

In [ ]:
np.trace(a)

np.float64(4.0)

In [ ]:
np.min(arr1)

np.int8(1)

In [ ]:
b=np.arange(16).reshape(4,4)
np.argmin(b)
k=np.min(arr1)
print(k)
b

1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.where(b<5,1,np.where(b==5,0,-1))

array([[ 1,  1,  1,  1],
       [ 1,  0, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
print(np.std(b))
print(np.var(b))

4.6097722286464435
21.25


In [ ]:
a2=np.arange(16).reshape(4,4)
a2[::-1]
a2[0:2,0:2]
a3=np.arange(12).reshape(2,2,3)
print(a3)
a3[0,-1,-1]
a3[0,0,0:-1:2]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([0])

In [ ]:
a3.reshape(12)
a3.reshape(-1)
a=np.arange(12).reshape(2,2,3)
a.resize(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a=np.array([1,2,3])
a.resize(6)
a

array([1, 2, 3, 0, 0, 0])

In [ ]:
a=np.arange(12).reshape(2,2,3)
print(a)
print(a.ravel())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a=np.arange(16).reshape(4,4)
b=np.linspace(16,32,8).reshape(4,2)
# print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 0.          1.          2.          3.         16.         18.28571429]
 [ 4.          5.          6.          7.         20.57142857 22.85714286]
 [ 8.          9.         10.         11.         25.14285714 27.42857143]
 [12.         13.         14.         15.         29.71428571 32.        ]]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.r_[a, b])
print(np.c_[a,b])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[1 2 3 4]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]



array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#splitting of arrays
a=np.arange(24).reshape(2,12)

np.vsplit(a,2)
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [ ]:
#copies and views
a=np.array([1,2,3,4,5])
b=a
print(b is a)
print(id(a))
print(id(b))

True
140220416436496
140220416436496


In [ ]:
a=10
b=a
b=9
print(a) #the above are only applicable to mutable ones

10


In [ ]:


def f(x):
    print(id(x))

print(id(a))
f(a)

10751144
10751144


In [ ]:
#view or copy
a=np.arange(16).reshape(4,4)
b=a.view()
b is a

False

In [ ]:
#advanced indexing
a = np.arange(12)**2
i = np.array([1, 1, 3, 8, 5])
a[i]


array([ 1,  1,  9, 64, 25])

In [ ]:
j = np.array([[3, 4], [9, 7]])
a[j]


array([[ 9, 16],
       [81, 49]])

In [ ]:
a=np.arange(4).reshape(2,2)
b=a>2
b

array([[False, False],
       [False,  True]])

In [ ]:
a[b]

array([3])

In [ ]:
a[b]=0
a

array([[0, 1],
       [2, 0]])

In [ ]:
a = np.arange(12).reshape(3, 4)
b1 = np.array([False, True, True])         # first dim selection
b2 = np.array([True, False, True, False])  # second dim selection
a[b1, :]                                   # selecting rows
a[b1]                                      # same thing
a[:, b2]                                   # selecting columns
a[b1, b2]                                  # a weird thing to do

array([ 4, 10])