<a href="https://colab.research.google.com/github/srikanthravipati27/ml/blob/main/l_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5.0],dtype=np.int8)
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],dtype=complex)
arr3=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [10, 11, 12]]])

In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
arr2

1
2
3
(5,)
(4, 4)
(2, 2, 3)


array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j],
       [13.+0.j, 14.+0.j, 15.+0.j, 16.+0.j]])

In [ ]:
arr1.dtype.itemsize  #

1

In [ ]:
arr1.data

In [ ]:
np.empty((2,3),dtype=int)

array([[          786645557,                   0,           785793744],
       [    132250169294080, 7092993904109055776, 7022303889196279146]])

In [ ]:
np.arange(5,30,4,dtype=float)
np.arange(0,2,0.9)

array([0. , 0.9, 1.8])

In [ ]:
from numpy import pi
np.linspace(0, 2, 9)
x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)
print(x)
print(f)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [ ]:
np.fromfunction(lambda i, j: 10*i + j, (3, 3))


array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.]])

In [ ]:
rng=np.random.default_rng()
rng.random(5)

array([0.88778294, 0.74789303, 0.33874751, 0.39561674, 0.86447921])

In [ ]:
rng.normal(loc=0, scale=1, size=5)


array([-1.16038905,  0.29886994, -0.66765636,  0.48535152,  0.54906318])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a=a.reshape(2,2,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
a=np.arange(5)
b=np.linspace(0,7,5,dtype=int)
print(b-a)
print(a**2)
print(b>8)

[0 0 1 2 3]
[ 0  1  4  9 16]
[False False False False False]


In [ ]:
ar1=np.arange(4).reshape(2,2)
ar2=np.linspace(2,7,4,dtype=int).reshape(2,2)
print(ar1)
print(ar2)
print(ar1*ar2)
print(ar1@ar2)
print(ar1.dot(ar2))

[[0 1]
 [2 3]]
[[2 3]
 [5 7]]
[[ 0  3]
 [10 21]]
[[ 5  7]
 [19 27]]
[[ 5  7]
 [19 27]]


In [51]:
a=np.eye(4)

In [52]:
np.trace(a)

np.float64(4.0)

In [57]:
np.min(arr1)

np.int8(1)

In [62]:
b=np.arange(16).reshape(4,4)
np.argmin(b)
k=np.min(arr1)
print(k)
b

1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.where(b<5,1,np.where(b==5,0,-1))

array([[ 1,  1,  1,  1],
       [ 1,  0, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [66]:
print(np.std(b))
print(np.var(b))

4.6097722286464435
21.25


In [76]:
a2=np.arange(16).reshape(4,4)
a2[::-1]
a2[0:2,0:2]
a3=np.arange(12).reshape(2,2,3)
print(a3)
a3[0,-1,-1]
a3[0,0,0:-1:2]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([0])

In [95]:
a3.reshape(12)
a3.reshape(-1)
a=np.arange(12).reshape(2,2,3)
a.resize(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [85]:
a=np.array([1,2,3])
a.resize(6)
a

array([1, 2, 3, 0, 0, 0])

In [96]:
a=np.arange(12).reshape(2,2,3)
print(a)
print(a.ravel())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
