<a href="https://colab.research.google.com/github/srikanthravipati27/ml/blob/main/l_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
a=torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(1,3)

tensor([[0., 0., 0.]])

In [6]:
torch.ones(1,3)

tensor([[1., 1., 1.]])

In [7]:
w=torch.randn(8,1,requires_grad=True)
print(w)

tensor([[-0.7574],
        [ 1.8790],
        [ 0.0338],
        [ 1.2144],
        [-0.9445],
        [-0.3091],
        [-1.4177],
        [ 0.8380]], requires_grad=True)


In [8]:
b=torch.randn(1,requires_grad=True)
print(b)

tensor([0.7284], requires_grad=True)


In [9]:
import torch
import torch.nn as nn

# Simple model: 3 inputs → 1 output (linear layer)
layer = nn.Linear(3, 1)

# Dummy input (1 sample, 3 features)
x = torch.tensor([[1.0, 2.0, 3.0]])

# Dummy target
y = torch.tensor([[1.0]])

# Loss function
criterion = nn.BCELoss()

# Forward pass
y_pred = torch.sigmoid(layer(x))
loss = criterion(y_pred, y)

# Backward pass
loss.backward()

# Print weights, biases, and their gradients
print("Weights:", layer.weight.data)
print("Bias:", layer.bias.data)
print("Gradients of weights:", layer.weight.grad)
print("Gradients of bias:", layer.bias.grad)


Weights: tensor([[-0.1646, -0.0971, -0.1420]])
Bias: tensor([0.1938])
Gradients of weights: tensor([[-0.6436, -1.2872, -1.9307]])
Gradients of bias: tensor([-0.6436])
